### ISSUE TITLE
After making a mistake once and the system displayed "Insufficient Memory", even restarting the computer couldn't make it run again.

### ISSUE THREAD

**Issue by huanli11** [mit-han-lab/ComfyUI-nunchaku#102]
It used to work normally. Once there was a mistake and it showed insufficient memory, even restarting the computer couldn't make it work again. It prompted insufficient memory. But I could run it before.

[2025-04-13 22:44:54.874] [warning] Failed to load safetensors using method MIO: CUDA error: out of memory (at C:\Users\muyang\Desktop\nunchaku-dev\src\Serialization.cpp:130)
[2025-04-13 22:45:02.011] [warning] Failed to load safetensors using method READ: CUDA error: out of memory (at C:\Users\muyang\Desktop\nunchaku-dev\src\Tensor.h:72)
[2025-04-13 22:45:09.279] [warning] Memory not pinned
!!! Exception during processing !!! CUDA error: out of memory (at C:\Users\muyang\Desktop\nunchaku-dev\src\Tensor.h:90)
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.6\ComfyUI\execution.py", line 345, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.6\ComfyUI\execution.py", line 220, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

**Comment by huanli11** [comment]
CUDA error: out of memory (at C:\Users\muyang\Desktop\nunchaku-dev\src\Tensor.h:90)

**Comment by J-Cott** [comment]
How much vram do you have? and have you got Cuda sysmem fallback turned on in the Nvidia control panel?

![Image](https://github.com/user-attachments/assets/31aecdd7-0d72-4e59-bfff-9e270b01e57c)

That might help.

**Comment by huanli11** [comment]
> 您有多少 vram？您是否在 Nvidia 控制面板中打开了 Cuda sysmem 回退？
> 
> ![Image](https://github.com/user-attachments/assets/31aecdd7-0d72-4e59-bfff-9e270b01e57c)
> 
> 这可能会有所帮助。

No? Later on, I deleted this workflow and it worked fine after that.

**Comment by lmxyy** [comment]
This should be resolved in [v0.3.0dev0](https://github.com/mit-han-lab/nunchaku/releases/tag/v0.3.0dev0) as in mit-han-lab/nunchaku#276 #40 and #100. Please upgrade both Nunchaku and ComfyUI-nunchaku to v0.3.0dev0.
