### ISSUE TITLE
[Bug]  CUDA error: out of memory (at C:\Users\muyang\Desktop\nunchaku-dev\src\Tensor.h:537)

### ISSUE THREAD

**Issue by jasoncow007** [mit-han-lab/ComfyUI-nunchaku#107]
### Checklist

- [x] 1. I have searched for related issues and FAQs (https://github.com/mit-han-lab/nunchaku/discussions/262) but was unable to find a solution.
- [ ] 2. The issue persists in the latest version.
- [ ] 3. Please note that without environment information and a minimal reproducible example, it will be difficult for us to reproduce and address the issue, which may delay our response.
- [ ] 4. If your report is a question rather than a bug, please submit it as a discussion at https://github.com/mit-han-lab/ComfyUI-nunchaku/discussions/new/choose. Otherwise, this issue will be closed.
- [ ] 5. I will do my best to describe the issue in English.

### Describe the Bug

comfyui loaded nodes without error, but when run, get this error :RuntimeError:
 CUDA error: out of memory (at C:\Users\muyang\Desktop\nunchaku-dev\src\Tensor.h:537)

BTW,I dont have the path mentioned in the error

### Environment

win11, python 3.11.6, pytorch 2.6+cuda12.6

### Reproduction Steps

[2025-04-14 23:47:09.903] [info] Initializing QuantizedFluxModel on device 0
[2025-04-14 23:47:09.950] [info] Loading weights from D:\ComfyUI-aki-v1.2\models\diffusion_models\svdq-int4-flux.1-fill-dev\transformer_blocks.safetensors
!!! Exception during processing !!! CUDA error: out of memory (at C:\Users\muyang\Desktop\nunchaku-dev\src\Tensor.h:537)
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\execution.py", line 345, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\execution.py", line 220, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\execution.py", line 192, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 181, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-nunchaku\nodes\models\flux.py", line 280, in load_model
    self.transformer = NunchakuFluxTransformer2dModel.from_pretrained(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\python\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\python\Lib\site-packages\nunchaku\models\transformers\transformer_flux.py", line 298, in from_pretrained
    m = load_quantized_module(
        ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\python\Lib\site-packages\nunchaku\models\transformers\transformer_flux.py", line 229, in load_quantized_module
    m.load(path)
RuntimeError: CUDA error: out of memory (at C:\Users\muyang\Desktop\nunchaku-dev\src\Tensor.h:537)

**Comment by Beowulfe222** [comment]
Been getting this same issue since 2.0 - and it's a weird one, sometimes it will work fine, and sometimes it will trigger. Once it triggers it usually takes 20-30 min to clear and start working again. Maybe related to memory not properly being freed somewhere?

It especially seems to happen if I try a call in the browser (generates fine), and then run the exact same workflow through API (fails with OOM). That's not the only case though, will happen even if I'm just generating through browser.

Shouldn't be running out of memory, as far as I can tell there's no reason for it. Running on a 4090 that has nothing else loaded on it (everything else is running on a secondary GPU).

Here's my full log (with some identifying details removed):

> [2025-04-13 12:47:21.151] [info]  Adding extra search path custom_nodes C:\Applications\ComfyUI\custom_nodes
> Adding extra search path download_model_base C:\Applications\ComfyUI\models
> Adding extra search path custom_nodes C:\Users\#####\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes
> 
> [2025-04-13 12:47:21.153] [info]  Setting output directory to: C:\#####\Output
> Setting input directory to: C:\#####\Input
> Setting user directory to: C:\Applications\ComfyUI\user
> 
> [2025-04-13 12:47:22.514] [info]  [START] Security scan
> [DONE] Security scan
> ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 
> [2025-04-13 12:47:22.515] [info]  2025-04-13 12:47:22.526
> ** Platform: Windows
> ** Python version: 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]
> ** Python executable: C:\Applications\ComfyUI\.venv\Scripts\python.exe
> ** ComfyUI Path: C:\Users\#####\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
> ** ComfyUI Base Folder Path: C:\Users\#####\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
> ** User directory: C:\Applications\ComfyUI\user
> ** ComfyUI-Manager config path: C:\Applications\ComfyUI\user\default\ComfyUI-Manager\config.ini
> ** Log path: C:\Applications\ComfyUI\user\comfyui.log
> 
> [2025-04-13 12:47:23.375] [error] [ComfyUI-Manager] Failed to restore comfyui-frontend-package
> expected str, bytes or os.PathLike object, not NoneType
> 
> [2025-04-13 12:47:23.376] [info]  
> Prestartup times for custom nodes:
>    2.2 seconds: C:\Users\#####\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Set cuda device to: 1
> 
> [2025-04-13 12:47:24.626] [info]  Checkpoint files will always be loaded safely.
> 
> [2025-04-13 12:47:24.759] [info]  Total VRAM 24564 MB, total RAM 65028 MB
> pytorch version: 2.6.0+cu126
> 
> [2025-04-13 12:47:25.809] [info]  xformers version: 0.0.29.post3
> Set vram state to: NORMAL_VRAM
> 
> [2025-04-13 12:47:25.812] [info]  Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
> 
> [2025-04-13 12:47:26.004] [info]  Using xformers attention
> 
> [2025-04-13 12:47:26.926] [info]  ComfyUI version: 0.3.27
> 
> [2025-04-13 12:47:26.953] [info]  [Prompt Server] web root: C:\Users\#####\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app
> 
> [2025-04-13 12:47:27.886] [error] C:\Applications\ComfyUI\.venv\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 2.0.5 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
>   check_for_updates()
> 
> [2025-04-13 12:47:28.026] [error] C:\Applications\ComfyUI\.venv\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
>   warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
> 
> [2025-04-13 12:47:28.669] [info]  Total VRAM 24564 MB, total RAM 65028 MB
> pytorch version: 2.6.0+cu126
> 
> [2025-04-13 12:47:28.671] [info]  xformers version: 0.0.29.post3
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
> 
> [2025-04-13 12:47:29.282] [info]  Nvidia APEX normalization not installed, using PyTorch LayerNorm
> 
> [2025-04-13 12:47:29.367] [error] [comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Applications\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
> 
> [2025-04-13 12:47:29.369] [error] [comfyui_controlnet_aux] | INFO -> Using symlinks: False
> [comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
> 
> [2025-04-13 12:47:29.388] [error] C:\Applications\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
>   warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
> 
> [2025-04-13 12:47:29.402] [info]  Traceback (most recent call last):
>   File "C:\Users\#####\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 2141, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 991, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 1128, in get_code
>   File "<frozen importlib._bootstrap_external>", line 1186, in get_data
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Applications\\ComfyUI\\custom_nodes\\temp\\__init__.py'
> 
> 
> [2025-04-13 12:47:29.404] [info]  Cannot import C:\Applications\ComfyUI\custom_nodes\temp module for custom nodes: [Errno 2] No such file or directory: 'C:\\Applications\\ComfyUI\\custom_nodes\\temp\\__init__.py'
> 
> [2025-04-13 12:47:29.936] [info]  WAS Node Suite: OpenCV Python FFMPEG support is enabled
> WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Applications\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
> 
> [2025-04-13 12:47:30.336] [info]  WAS Node Suite: Finished. Loaded 220 nodes successfully.
> 
> 	"Art is the daughter of freedom." - Friedrich Schiller
> 
> [2025-04-13 12:47:30.337] [info]  
> 
> [2025-04-13 12:47:30.359] [info]  ### Loading: ComfyUI-Manager (V3.30.4)
> 
> [2025-04-13 12:47:30.360] [info]  [ComfyUI-Manager] network_mode: public
> ### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
> 
> [2025-04-13 12:47:30.367] [info]  
> Import times for custom nodes:
> 
> [2025-04-13 12:47:30.368] [info]     0.0 seconds (IMPORT FAILED): C:\Applications\ComfyUI\custom_nodes\temp
>    0.0 seconds: C:\Applications\ComfyUI\custom_nodes\comfyui-openpose-editor
>    0.0 seconds: C:\Users\#####\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
>    0.0 seconds: C:\Applications\ComfyUI\custom_nodes\x-flux-comfyui
>    0.0 seconds: C:\Users\#####\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
>    0.0 seconds: C:\Applications\ComfyUI\custom_nodes\comfyui_controlnet_aux
>    0.0 seconds: C:\Applications\ComfyUI\custom_nodes\comfyui-kjnodes
>    0.1 seconds: C:\Applications\ComfyUI\custom_nodes\ComfyUI-nunchaku
>    0.2 seconds: C:\Applications\ComfyUI\custom_nodes\ComfyUI-IPAdapter-Flux
>    0.6 seconds: C:\Applications\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux
>    0.9 seconds: C:\Applications\ComfyUI\custom_nodes\was-node-suite-comfyui
>    1.0 seconds: C:\Applications\ComfyUI\custom_nodes\comfyui-inspyrenet-rembg
> 
> [2025-04-13 12:47:30.369] [info]  
> 
> [2025-04-13 12:47:30.376] [info]  Starting server
> 
> 
> [2025-04-13 12:47:30.377] [info]  To see the GUI go to: http://127.0.0.1:8818
> 
> [2025-04-13 12:47:30.522] [info]  [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
> 
> [2025-04-13 12:47:30.558] [info]  [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
> 
> [2025-04-13 12:47:30.581] [info]  [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
> 
> [2025-04-13 12:47:30.605] [info]  [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
> 
> [2025-04-13 12:47:30.651] [info]  [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> 
> [2025-04-13 12:47:31.901] [info]  []
> []
> 
> [2025-04-13 12:47:34.213] [info]  FETCH ComfyRegistry Data: 5/81
> 
> [2025-04-13 12:47:37.559] [info]  FETCH ComfyRegistry Data: 10/81
> 
> [2025-04-13 12:47:40.949] [info]  FETCH ComfyRegistry Data: 15/81
> 
> [2025-04-13 12:47:44.289] [info]  FETCH ComfyRegistry Data: 20/81
> 
> [2025-04-13 12:47:47.606] [info]  FETCH ComfyRegistry Data: 25/81
> 
> [2025-04-13 12:47:50.926] [info]  FETCH ComfyRegistry Data: 30/81
> 
> [2025-04-13 12:47:54.284] [info]  FETCH ComfyRegistry Data: 35/81
> 
> [2025-04-13 12:47:57.618] [info]  FETCH ComfyRegistry Data: 40/81
> 
> [2025-04-13 12:48:01.363] [info]  FETCH ComfyRegistry Data: 45/81
> 
> [2025-04-13 12:48:04.681] [info]  FETCH ComfyRegistry Data: 50/81
> 
> [2025-04-13 12:48:08.044] [info]  FETCH ComfyRegistry Data: 55/81
> 
> [2025-04-13 12:48:11.379] [info]  FETCH ComfyRegistry Data: 60/81
> 
> [2025-04-13 12:48:14.714] [info]  FETCH ComfyRegistry Data: 65/81
> 
> [2025-04-13 12:48:18.139] [info]  FETCH ComfyRegistry Data: 70/81
> 
> [2025-04-13 12:48:21.506] [info]  FETCH ComfyRegistry Data: 75/81
> 
> [2025-04-13 12:48:24.833] [info]  FETCH ComfyRegistry Data: 80/81
> 
> [2025-04-13 12:48:26.021] [info]  FETCH ComfyRegistry Data [DONE]
> 
> [2025-04-13 12:48:26.094] [info]  [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
> 
> [2025-04-13 12:48:26.114] [info]  nightly_channel: 
> https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/remote
> 
> [2025-04-13 12:48:26.115] [info]  FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> [2025-04-13 12:48:26.332] [info]   [DONE]
> 
> [2025-04-13 12:48:26.371] [info]  [ComfyUI-Manager] All startup tasks have been completed.
> 
> [2025-04-13 12:48:34.882] [info]  got prompt
> 
> [2025-04-13 12:48:34.918] [info]  Using xformers attention in VAE
> 
> [2025-04-13 12:48:34.920] [info]  Using xformers attention in VAE
> 
> [2025-04-13 12:48:35.112] [info]  VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
> 
> [2025-04-13 12:48:35.139] [info]  GPU 0 (NVIDIA GeForce RTX 4090) Memory: 24563.5 MiB
> Disable CPU offload
> 
> [2025-04-13 12:48:35.263] [info]  [2025-04-13 12:48:35.263] [info] Initializing QuantizedFluxModel on device 0
> 
> [2025-04-13 12:48:35.357] [info]  [2025-04-13 12:48:35.357] [info] Loading weights from C:\Applications\ComfyUI\models\diffusion_models\svdq-int4-flux.1-dev\transformer_blocks.safetensors
> 
> [2025-04-13 12:48:36.592] [error] !!! Exception during processing !!! CUDA error: out of memory (at C:\Users\muyang\Desktop\nunchaku-dev\src\Tensor.h:393)
> 
> [2025-04-13 12:48:36.593] [error] Traceback (most recent call last):
>   File "C:\Users\#####\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\#####\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\#####\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "C:\Users\#####\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Applications\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\flux.py", line 280, in load_model
>     self.transformer = NunchakuFluxTransformer2dModel.from_pretrained(
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Applications\ComfyUI\.venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "C:\Applications\ComfyUI\.venv\Lib\site-packages\nunchaku\models\transformers\transformer_flux.py", line 298, in from_pretrained
>     m = load_quantized_module(
>         ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Applications\ComfyUI\.venv\Lib\site-packages\nunchaku\models\transformers\transformer_flux.py", line 229, in load_quantized_module
>     m.load(path)
> RuntimeError: CUDA error: out of memory (at C:\Users\muyang\Desktop\nunchaku-dev\src\Tensor.h:393)


[2025-04-13 12:48:36.594] [info]  Prompt executed in 1.71 seconds

**Comment by Natural-Q** [comment]
同样的问题，试过其他整合包也会同样报错，所以试想是不是在comfyui外部的电脑系统有什么环境没有安装成功，找到解决方案麻烦说下，谢谢!

**Comment by fanxu525** [comment]
我也遇到了同样的问题，有时候连续几次都能成功运行，有时候又连续几次都这么报错
I have also encountered the same problem, sometimes it can run successfully several times in a row, and sometimes it reports the same error several times in a row

**Comment by fanxu525** [comment]
> 我也遇到了同样的问题，有时候连续几次都能成功运行，有时候又连续几次都这么报错 I have also encountered the same problem, sometimes it can run successfully several times in a row, and sometimes it reports the same error several times in a row

哦~我感觉我好像找到原因了~我是一个愚蠢的新手，不知道大家出现的问题会不会和我是相同原因。可能是因为我没有使用正确的工作流，当我使用nunkucha插件文件夹内的工作流（".\custom_nodes\ComfyUI-nunchaku\workflows\nunchaku-flux.1-dev.json"）时，问题似乎被解决了。我这边的理解是，在使用nunchaku时，clip编译要使用nunchaku的clip，即Nunchaku Text Encoder Loader节点
-------
Oh~I feel like I've found the reason~I'm a stupid beginner, I don't know if everyone's problems are the same as mine. Perhaps because I didn't use the correct workflow, the problem seemed to be resolved when I used the workflow in the nunkucha plugin folder (". \ custom_nodes \ ComfyUI nunchaku \ workflows \ nunchaku-flux. 1-dev. json"). My understanding here is that when using nunkaku, the clip compilation should use nunkaku's clip, which is the nunkaku Text Encoder Loader node

![Image](https://github.com/user-attachments/assets/cf3ad476-81b7-49e8-83af-898d94de4092)

**Comment by lmxyy** [comment]
Could you try this in our [FAQ](https://github.com/mit-han-lab/nunchaku/blob/main/docs/faq.md#out-of-memory-or-slow-model-loading-egmit-han-labnunchaku249-mit-han-labnunchaku311-mit-han-labnunchaku276) to see if it helps:

> Try upgrading your CUDA driver and try setting the environment variable NUNCHAKU_LOAD_METHOD to either READ or READNOPIN.
> Some references: https://github.com/mit-han-lab/nunchaku/issues/249 https://github.com/mit-han-lab/nunchaku/issues/311 https://github.com/mit-han-lab/nunchaku/pull/276

I will close this issue for now. If the error persists or you have other questions, feel free to open new ones.
