### ISSUE TITLE
[Bug]Used Dev version， Failed to load safetensors using method MIO: CUDA error: operation not supported

### ISSUE THREAD

**Issue by Jinnnmh** [mit-han-lab/ComfyUI-nunchaku#211]
### Checklist

- [x] 1. I have searched for related issues and FAQs (https://github.com/mit-han-lab/nunchaku/blob/main/docs/faq.md) but was unable to find a solution.
- [x] 2. The issue persists in the latest version.
- [x] 3. Please note that without environment information and a minimal reproducible example, it will be difficult for us to reproduce and address the issue, which may delay our response.
- [x] 4. If your report is a question rather than a bug, please submit it as a discussion at https://github.com/mit-han-lab/ComfyUI-nunchaku/discussions/new/choose. Otherwise, this issue will be closed.
- [x] 5. I will do my best to describe the issue in English.

### Describe the Bug

![Image](https://github.com/user-attachments/assets/daf4a1ed-17d1-467d-b2ff-1041c054b582)

### Environment

![Image](https://github.com/user-attachments/assets/059f8561-f02f-4519-81d2-1978f6af5140)
windows10  RTX4080S  pytorch version: 2.7.0+cu128 python312 

### Reproduction Steps

![Image](https://github.com/user-attachments/assets/3d78940f-6fd4-4e34-be27-c9e735f80897)

**Comment by lmxyy** [comment]
Have you tried this: https://github.com/mit-han-lab/nunchaku/blob/main/docs/faq.md#out-of-memory-or-slow-model-loading-egmit-han-labnunchaku249-mit-han-labnunchaku311-mit-han-labnunchaku276

![Image](https://github.com/user-attachments/assets/4f9c11d6-0044-4144-a4e3-9fa9d42cbc80)

**Comment by dioscuri0860** [comment]
> Have you tried this: https://github.com/mit-han-lab/nunchaku/blob/main/docs/faq.md#out-of-memory-or-slow-model-loading-egmit-han-labnunchaku249-mit-han-labnunchaku311-mit-han-labnunchaku276
> 
> ![Image](https://github.com/user-attachments/assets/4f9c11d6-0044-4144-a4e3-9fa9d42cbc80)

It works fine on systems with 4060ti 16GB of vga in the same Ubuntu environment.
The system that doesn't work is 4080 16GB, but the only difference is that it happened after installing dev wheel on 4080 system.
I removed dev wheel and reinstalled 0.2 wheel but it still doesn't work.
When the dev wheel was first installed, gpu ram accounted for 97%, but it worked and CUDA OOM errors began to occur after creating multiple batches of images.
I downloaded and ran the FP4 model yesterday, but comfyui didn't work after the memory pinn message, so I restarted comfyui and changed FP4 to int4, and successfully created the image after setting up cpu offload auto.
Of course, gpu ram usage is 97-99%

**Comment by dioscuri0860** [comment]
If you're using window11 python_embedded and swarmUI, I've solved it like this.

![Image](https://github.com/user-attachments/assets/7047169f-20c2-4830-bb60-38f8dae126c7)
1. change update mode. stable. and click update all.
2. delete custom_nodes\ComfyUI-nunchaku.
3. swarmUI\dlbackend\comfy\update folder, run update_comfyui_and_python_dependencies.bat
4. If the pytorch version changed to 2.7, reinstall the latest nunchaku dev wheel as well.
5. restart ComfyUI
6. open comfyUI manager, install nunchaku select latest.
7. If an import failed occurs. delete python_embeded\lib\site-packages\
BitsAndBytes*
