### ISSUE TITLE
[Bug] The first attempt is OOM

### ISSUE THREAD

**Issue by dioscuri0860** [mit-han-lab/ComfyUI-nunchaku#259]
### Checklist

- [x] 1. I have searched for related issues and FAQs (https://github.com/mit-han-lab/nunchaku/blob/main/docs/faq.md) but was unable to find a solution.
- [x] 2. The issue persists in the latest version.
- [x] 3. Please note that without environment information and a minimal reproducible example, it will be difficult for us to reproduce and address the issue, which may delay our response.
- [x] 4. If your report is a question rather than a bug, please submit it as a discussion at https://github.com/mit-han-lab/ComfyUI-nunchaku/discussions/new/choose. Otherwise, this issue will be closed.
- [x] 5. I will do my best to describe the issue in English.

### Describe the Bug

![Image](https://github.com/user-attachments/assets/a55f9b02-a6ae-4141-97f0-faae0a6cf811)
got prompt
Using xformers attention in VAE
Using xformers attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
GPU 0 (NVIDIA GeForce RTX 4080) Memory: 16375.5 MiB
VRAM > 14GiB，disable CPU offload
Injecting quantized module
model_type FLUX
FETCH ComfyRegistry Data: 40/88
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
!!! Exception during processing !!! Allocation on device 
Traceback (most recent call last):
  File "G:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\text_encoder.py", line 279, in load_text_encoder
    clip = load_text_encoder_state_dicts(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\text_encoder.py", line 215, in load_text_encoder_state_dicts
    clip.cond_stage_model.to_empty(
  File "G:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1207, in to_empty
    return self._apply(
           ^^^^^^^^^^^^
  File "G:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 915, in _apply
    module._apply(fn)
  File "G:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 915, in _apply
    module._apply(fn)
  File "G:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 915, in _apply
    module._apply(fn)
  File "G:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 942, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "G:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1208, in <lambda>
    lambda t: torch.empty_like(t, device=device), recurse=recurse
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device 

Got an OOM, unloading all loaded models.
Prompt executed in 2.84 seconds

### Environment

2025-06-06 20:17:48.796 [ComfyUI-2] [STDOUT] ** Platform: Windows
2025-06-06 20:17:48.796 [ComfyUI-2] [STDOUT] ** Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
2025-06-06 20:17:48.796 [ComfyUI-2] [STDOUT] ** Python executable: G:\SwarmUI\dlbackend\comfy\python_embeded\python.exe
2025-06-06 20:17:48.796 [ComfyUI-2] [STDOUT] ** ComfyUI Path: G:\SwarmUI\dlbackend\comfy\ComfyUI
2025-06-06 20:17:48.796 [ComfyUI-2] [STDOUT] ** ComfyUI Base Folder Path: G:\SwarmUI\dlbackend\comfy\ComfyUI
2025-06-06 20:17:48.796 [ComfyUI-2] [STDOUT] ** User directory: G:\SwarmUI\dlbackend\comfy\ComfyUI\user
2025-06-06 20:17:48.796 [ComfyUI-2] [STDOUT] ** ComfyUI-Manager config path: G:\SwarmUI\dlbackend\comfy\ComfyUI\user\default\ComfyUI-Manager\config.ini
2025-06-06 20:17:48.796 [ComfyUI-2] [STDOUT] ** Log path: G:\SwarmUI\dlbackend\comfy\ComfyUI\user\comfyui.log
2025-06-06 20:17:50.805 [ComfyUI-2] [STDERR] Checkpoint files will always be loaded safely.
2025-06-06 20:17:50.904 [ComfyUI-2] [STDERR] Total VRAM 16376 MB, total RAM 65301 MB
2025-06-06 20:17:50.904 [ComfyUI-2] [STDERR] pytorch version: 2.7.1+cu128
2025-06-06 20:17:52.016 [ComfyUI-2] [STDERR] xformers version: 0.0.30
2025-06-06 20:17:52.016 [ComfyUI-2] [STDERR] Set vram state to: NORMAL_VRAM
2025-06-06 20:17:52.016 [ComfyUI-2] [STDERR] Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync

### Reproduction Steps

On the first attempt, OOM occurs every time.
run try again, it will work normally.
but. Memory usage is high.
Nunchaku Text Encoder Loader V2 <-- usage Vram 99%
nuchaku wheel dev and ComfyUI Node nightly update latest
I pytorch update and installed xformers just in case.
Nunchaku Text Encoder Loader works fine.

**Comment by josemerinom** [comment]
I know the issue was fixed and closed in a previous post.
Today I updated node
git clone https://github.com/mit-han-lab/ComfyUI-nunchaku
And it didn't work.
I tried using the dev repository
git clone https://github.com/mit-han-lab/ComfyUI-nunchaku --branch dev
But it didn't work for me, and I can't load the T5 AWQ.

**Comment by tritant** [comment]
Exactly the same thing for me, if I use t5xxl fp16, the first test causes an oom (the following ones work), the problem disappears if I use t5xxl fp8

**Comment by lmxyy** [comment]
Hopefully, mit-han-lab/ComfyUI-nunchaku#256 should fix this. By the way, you can also use the t5xxl fp8. It should be compatible.

**Comment by lmxyy** [comment]
Our 4-bit T5 model may exhibit some fidelity loss, as it is primarily designed to reduce GPU memory usage.

**Comment by PrometheusDante** [comment]
That happened to me too with the fp16 version, why I kept using the dual clip loader I used before, without issues 😅
Are there any downsides to doing that?

**Comment by dioscuri0860** [comment]
> That happened to me too with the fp16 version, why I kept using the dual clip loader I used before, without issues 😅 Are there any downsides to doing that?

There is no disadvantage, but I think I saw that the existing node will be deleted from the version of nunchaku 0.4.

ps: Install both the 0.3.1 wheel and the comfyui node. I think it's resolved.
